#!/usr/bin/env python3
"""Generate the vendored PSL artifacts for all three UriMatch surfaces.

Reads  spec/psl/public_suffix_list.dat  (the upstream snapshot, vendored verbatim) and emits
three GENERATED-BUT-COMMITTED data files carrying the identical rule set + snapshot hash:

    core/src/commonMain/kotlin/io/silencelen/andvari/core/client/autofill/PslData.kt
    web/src/vault/pslData.ts
    extension/src/pslData.ts

Design (docs/design/2026-07-10-etld1-psl-matching.md): data files are DUMB — one joined
ASCII string + a sha256 — all parsing/algorithm lives in the three UriMatch impls, and the
shared vector file records the same hash so any drift between the copies fails tests.

Refresh procedure (spec/psl/README.md): re-vendor the .dat, re-run this script, run the
gates. Never edit the generated files by hand.
"""

from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DAT = ROOT / "spec" / "psl" / "public_suffix_list.dat"
MAX_TOTAL_BYTES = 400_000  # bound against upstream bloat (design §pipeline)
KOTLIN_CHUNK = 48_000  # << the 64 KiB constant-pool UTF-8 limit

KT_OUT = ROOT / "core/src/commonMain/kotlin/io/silencelen/andvari/core/client/autofill/PslData.kt"
WEB_OUT = ROOT / "web/src/vault/pslData.ts"
EXT_OUT = ROOT / "extension/src/pslData.ts"


def ascii_label(label: str) -> str:
    """Punycode-normalize one label (IDNA2003 via encodings.idna; the residual IDNA2003-vs-
    UTS46 divergence — ß-class rules — can only ever under-match and is README-documented,
    A12). Lowercases FIRST (encodings.idna passes ASCII through unlowercased); fails LOUDLY
    on empty/oversized labels so a broken refresh can't ship a silently-shrunken list."""
    label = label.lower()
    if not label:
        raise SystemExit(f"FAIL: empty label in PSL rule (garbled snapshot?)")
    if all(ord(c) < 128 for c in label):
        if len(label) > 63:
            raise SystemExit(f"FAIL: label >63 chars in PSL rule: {label!r}")
        return label
    try:
        out = label.encode("idna").decode("ascii")
    except (UnicodeError, UnicodeDecodeError):
        try:
            out = "xn--" + label.encode("punycode").decode("ascii")
        except UnicodeError as e:
            raise SystemExit(f"FAIL: cannot punycode PSL label {label!r}: {e}")
    return out.lower()


def normalize_rule(rule: str) -> str:
    prefix = ""
    if rule.startswith("!"):
        prefix, rule = "!", rule[1:]
    elif rule.startswith("*."):
        prefix, rule = "*.", rule[2:]
    return prefix + ".".join(ascii_label(l) for l in rule.split("."))


def main() -> int:
    raw = DAT.read_text(encoding="utf-8")
    version = next((l.split("VERSION:", 1)[1].strip() for l in raw.splitlines() if "VERSION:" in l), "unknown")

    rules: set[str] = set()
    for line in raw.splitlines():
        line = line.strip()
        if not line or line.startswith("//"):
            continue
        # PSL format: a rule reads up to the FIRST whitespace — anything after is annotation.
        # Without this split a "foo.bar  // note" line would store an unmatchable rule string
        # (silently DROPPING the real rule — an over-match hazard, not an under-match one).
        rule = normalize_rule(line.split()[0])
        # Charset whitelist: these strings flow verbatim into a Kotlin raw string and a TS
        # template literal. Post-normalization, every label must be lowercase LDH (+ "_",
        # which the private section really uses) — anything else fails the refresh loudly.
        body = rule.removeprefix("!").removeprefix("*.")
        if not re.fullmatch(r"[a-z0-9_.-]+", body):
            raise SystemExit(f"FAIL: rule has out-of-whitelist chars after normalization: {rule!r}")
        rules.add(rule)

    joined = "\n".join(sorted(rules))
    digest = hashlib.sha256(joined.encode("ascii")).hexdigest()
    if len(joined) > MAX_TOTAL_BYTES:
        print(f"FAIL: joined rules {len(joined)} bytes > bound {MAX_TOTAL_BYTES}", file=sys.stderr)
        return 1

    header = (
        f"GENERATED by scripts/gen-psl.py from spec/psl/public_suffix_list.dat — DO NOT EDIT.\n"
        f"Upstream VERSION: {version} | rules: {len(rules)} | sha256(joined): {digest}"
    )

    # ---- Kotlin (chunked: a single string constant caps at 65,535 modified-UTF-8 bytes).
    # Chunks are NON-const vals joined via joinToString at runtime: `const val` concatenation
    # constant-folds at compile time back into one >64 KiB constant and fails the build (A9).
    chunks = [joined[i : i + KOTLIN_CHUNK] for i in range(0, len(joined), KOTLIN_CHUNK)]
    kt_consts = "\n\n".join(
        f'private val PSL_CHUNK_{i}: String = """{c}"""' for i, c in enumerate(chunks)
    )
    kt_join = "listOf(" + ", ".join(f"PSL_CHUNK_{i}" for i in range(len(chunks))) + ").joinToString(\"\")"
    KT_OUT.write_text(
        f"""// {header.replace(chr(10), chr(10) + '// ')}
package io.silencelen.andvari.core.client.autofill

{kt_consts}

object PslData {{
    /** sha256 of the joined rule list — pinned by spec/test-vectors/urimatch-etld1.json. */
    const val PSL_SNAPSHOT_HASH: String = "{digest}"

    /** The newline-joined, sorted, punycode-normalized PSL rules (ICANN + private). */
    val joined: String by lazy {{ {kt_join} }}
}}
""",
        encoding="utf-8",
    )

    ts_body = f"""// {header.replace(chr(10), chr(10) + '// ')}

/** sha256 of the joined rule list — pinned by spec/test-vectors/urimatch-etld1.json. */
export const PSL_SNAPSHOT_HASH = "{digest}";

/** The newline-joined, sorted, punycode-normalized PSL rules (ICANN + private). */
export const PSL_RULES_JOINED = `{joined}`;
"""
    WEB_OUT.write_text(ts_body, encoding="utf-8")
    EXT_OUT.write_text(ts_body, encoding="utf-8")

    print(f"OK version={version} rules={len(rules)} joined={len(joined)}B sha256={digest}")
    print(f"wrote {KT_OUT.relative_to(ROOT)} ({len(chunks)} chunks), {WEB_OUT.relative_to(ROOT)}, {EXT_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
